"""add language to posts

Revision ID: 945975999366
Revises: 87259f20052c
Create Date: 2020-11-03 19:34:00.644127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945975999366'
down_revision = '87259f20052c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
